export const sampleRecipes = [
  {
    id: "lemon-chicken-tray-bake",
    title: "Lemon Chicken Tray Bake",
    mealTypes: ["dinner"],
    effort: "low",
    repeatFrequency: "regular",
    weatherFit: ["mixed", "hot"],
    leftovers: "good",
    ingredients: ["chicken thighs", "lemons", "potatoes", "green beans", "parsley"],
  },
  {
    id: "lentil-soup",
    title: "Lentil Soup",
    mealTypes: ["dinner", "lunch"],
    effort: "low",
    repeatFrequency: "regular",
    weatherFit: ["cool", "rainy", "mixed"],
    leftovers: "good",
    ingredients: ["lentils", "carrots", "celery", "onion", "vegetable stock"],
  },
  {
    id: "salmon-rice-bowls",
    title: "Salmon Rice Bowls",
    mealTypes: ["dinner"],
    effort: "medium",
    repeatFrequency: "occasional",
    weatherFit: ["hot", "mixed"],
    leftovers: "okay",
    ingredients: ["salmon", "rice", "cucumber", "avocado", "soy sauce"],
  },
  {
    id: "mushroom-risotto",
    title: "Mushroom Risotto",
    mealTypes: ["dinner"],
    effort: "medium",
    repeatFrequency: "occasional",
    weatherFit: ["cool", "rainy"],
    leftovers: "okay",
    ingredients: ["arborio rice", "mushrooms", "parmesan", "white wine", "stock"],
  },
  {
    id: "summer-noodle-salad",
    title: "Summer Noodle Salad",
    mealTypes: ["dinner", "lunch"],
    effort: "low",
    repeatFrequency: "regular",
    weatherFit: ["hot"],
    leftovers: "good",
    ingredients: ["rice noodles", "cucumber", "herbs", "peanuts", "lime"],
  },
  {
    id: "beef-stew",
    title: "Beef Stew",
    mealTypes: ["dinner"],
    effort: "high",
    repeatFrequency: "rare",
    weatherFit: ["cool", "rainy"],
    leftovers: "good",
    ingredients: ["beef", "carrots", "potatoes", "onion", "red wine"],
  },
  {
    id: "fried-rice",
    title: "Fried Rice",
    mealTypes: ["lunch", "dinner"],
    effort: "low",
    repeatFrequency: "regular",
    weatherFit: ["mixed", "hot", "cool"],
    leftovers: "okay",
    ingredients: ["rice", "eggs", "peas", "spring onions", "soy sauce"],
  },
  {
    id: "tomato-pasta",
    title: "Tomato Pasta",
    mealTypes: ["dinner", "lunch"],
    effort: "low",
    repeatFrequency: "regular",
    weatherFit: ["mixed"],
    leftovers: "good",
    ingredients: ["pasta", "tomatoes", "garlic", "basil", "parmesan"],
  },
  {
    id: "chickpea-curry",
    title: "Chickpea Curry",
    mealTypes: ["dinner"],
    effort: "medium",
    repeatFrequency: "occasional",
    weatherFit: ["cool", "rainy", "mixed"],
    leftovers: "good",
    ingredients: ["chickpeas", "coconut milk", "spinach", "rice", "curry paste"],
  },
];
